embed_assets: on
javascript_compressor: yui

javascripts:
  common:
    - public/javascripts/jquery/jquery-1.6.2.js
    - public/javascripts/jquery-ui-1.8.11.custom/js/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/jquery/plugins/jquery.hoverIntent.js
    - public/javascripts/jquery/plugins/jquery.ui.totop.js
    - public/javascripts/jquery-ujs/rails.js
    - public/javascripts/jquery/plugins/jquery.jnotify.js
    - public/javascripts/jquery/plugins/jquery.ui.selectmenu.js
    - public/javascripts/katello.js
    - public/javascripts/application.js
    - public/javascripts/jquery/plugins/jquery.linkHover.js
    - public/javascripts/jquery/plugins/jquery.sparkline.min.js
    - public/javascripts/jquery/plugins/jquery.jscrollpane.js
  html5:
    - public/javascripts/html5.js
  dashboard:
    - public/javascripts/headpin.sparkline.js
  katello_client:
    - public/javascripts/katello_client.js
  login:
    - public/javascripts/login.js
  systems:
    - public/javascripts/systems.js
    - public/javascripts/jquery/plugins/ui.spinner.js
  system_subscriptions:
    - public/javascripts/system_subscriptions.js
  form:
    - public/javascripts/jquery/plugins/jquery.form.js
  treetable:
    - public/javascripts/jquery/plugins/jquery.treeTable.js
  panel:
    - public/javascripts/jquery/plugins/jquery.ba-resize.js
    - public/javascripts/panel.js
  notices:
    - public/javascripts/notices.js
    - public/javascripts/jquery/plugins/jquery.periodicalupdater.js
  password:
    - public/javascripts/jquery/plugins/jquery.simplePassMeter.js
  user:
    - public/javascripts/user.js
  user_edit:
    - public/javascripts/user_edit.js
  role:
    - public/javascripts/role.js
    - public/javascripts/slidingtree.js
    - public/javascripts/role_sliding_tree.js
  role_edit:
    - public/javascripts/jquery/plugins/jquery.sortElements.js
    - public/javascripts/role_edit.js
  org_edit:
    - public/javascripts/org_edit.js
  activation_key:
    - public/javascripts/activation_key.js
  subscription:
    - public/javascripts/subscription.js
    - public/javascripts/headpin.sparkline.js
  edit:
    - public/javascripts/jquery/plugins/jquery.jeditable.js
    - public/javascripts/jquery.jeditable.helpers.js
    #- public/javascripts/jquery/plugins/jquery.jeditable.ajaxupload.js
    #- public/javascripts/jquery/plugins/jquery.ajaxfileupload.js
  multiselect:
    - public/javascripts/jquery/plugins/jquery.ui.multiselect.js
  fancyqueries:
    - public/javascripts/jquery/plugins/jquery.fancyqueries.js
    - public/javascripts/search.js
  scroll_pane:
    - public/javascripts/jquery/plugins/jquery.mousewheel.js
    - public/javascripts/jquery/plugins/jquery.jscrollpane.min.js
    - public/javascripts/scroll_pane.js
  bbq:
    - public/javascripts/jquery/plugins/jquery.ba-bbq.js

stylesheets:
  common:
    - public/javascripts/jquery-ui-1.8.11.custom/css/custom-theme/jquery-ui-1.8.11.custom.css
    - public/stylesheets/jquery.loadmask.css
    - public/stylesheets/compiled/ie.css
    - public/stylesheets/jquery.jnotify.css
    - public/stylesheets/jquery.treeTable.css
    - public/stylesheets/compiled/headpin.css
    - public/stylesheets/jquery.jscrollpane.css
  fancyqueries:
    - public/stylesheets/compiled/fancyqueries.css
  loginpage:
    - public/stylesheets/compiled/sections/loginpage.css
  dashboard:
    - public/stylesheets/compiled/sections/dashboard.css
  subscriptions:
    - public/stylesheets/compiled/sections/subscriptions.css
  systems:
    - public/stylesheets/compiled/sections/systems.css
    - public/stylesheets/ui.spinner.css
  admin:
    - public/stylesheets/compiled/sections/admin.css
  scroll_pane:
    - public/stylesheets/jquery.jscrollpane.css

